---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keda-rabbitmq-secret
  namespace: cloud-media
spec:
  encryptedData:
    host: AgASNo39fg2r6grmwCKVdw+4Qrdipau+dfmSBmF0DxwqYPZjOWKSyW3v2FLo4rCWjh8DtPq76VTCrWBMYiJ0E7ODvYVTINtHs+PjK5VzWpr8vaHDALi0kNBwztdPIbWbemLg1En0fyTo5dy7UyrPPWJ5sRPzhIMZOoIXARqXnfI0VbEsft7d2pH0hcQP+cgjbl9Z72LYYF0XV73X/2xQILlaIA81AoKBCS7t8ZxOoL7ovBe0TQJiqI5JrSGazUizT7CV/QX7X+R8DaFGFFTgydyvGEO/9Wv/6vHYwyc0zgNnsodODJ/h5qHSsyGtaBo0x8IDGrA+42FDLakkspvKHXXLvXxTdo4eyat1WpkL2UWrZV8VoL6kFtJvNzAgavvzbZIUkX34UqKkE00biTlie/4eeYChz0GFEbCbZra1S2PusCCJccpEOIlJ5qnnovSwSCq4NlxsTOZi8naGEWLjVsTjkaD7XvL/u6uk877S/XkIzqEFvwljdE4tKwj9bb+qmR4wnwbDcQkNOKdG/AVZq1L/xMCdiF/cBbLYAfZTfx6vyaOsukECwFI7yyIVFaONmoCe89PgaN0ffvtjnlvAHrKGUWJTRGjx7nDe6467u+TxtCeitbfgukUZwj54AsWOBftvIMNnrNU2UnLjks/V0sjI4AO3vl/r+Gc/m6hpo+lRKA8T/e6oSgQQd86PBfC2Do0+WVldDGzICAGmUwsoVxR2ZyNHJpkKLDtFTDiQVJR51MrcgFbZwEDzQ50u8LHgDtnzgorfF0xvmY4x/PHmMI/+sRZh7hXCcg==
  template:
    metadata:
      name: keda-rabbitmq-secret
      namespace: cloud-media
    type: Opaque
