---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: cloud-media
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA1F3idnKd319vqqVYb39dN/61bK/DVlgCvLDGHFHjeEFiZ9hpVfB+CKfxPcuoUkb5y4LsUiQLojpWHXY3yLMaLZdRRzeHUC66bTX4GowXOV6kUy2Ssg5YbSDK2kLxHwQi/WDRa8MdpjQf3CJjyosD3UUscvTlIgyBy+fe1baOKTwC9kuGAVk+TVfpYIi5pCqN+pCLPh5nidaxN060R+SFOenX0ZsgF8XE7G+4Hmhoh9FCKEd1PWePQ/0uGy3hwUaGSre6R3Hi8sJROvVyB+5brIyBmJ5MR2fDjy3RffECCoussgeq77U2f9c4x189FDXJ+j+6qZO6aC4gh6JiEBE+NVqhTpXT9FnqRsbDi/ETZsVChhFm7Sm8jTGele7XK7xaDklQdWuMayYD4NlaX6ZbAnJEWubw4ebfzdmyeGCkgs90ccKqCIaBRM+FXEi5J6wNLJHJ32t+9a55xikb9ITdmWCFzaxyJc07JL0Q/4xWzIWz5Bzx/zEQdY9S3U6MEzqch2UTClZpmaWoV61ZFbekHCrh2BMbiR6lOw+wkhr4UmATEHRE9V1ceYgLQ70mbNf3WmxA1l1Cx1u6vVRQa6EzHfvps+tLrWZw5arurpbZ5YRGqMV15wo/fRq7j3dUpHW61IFSxWaqwSk7jpFY1lz+xcEWTe+OG2XAoQO/KSjMHhfc/O0PvTWUSzW7xgBwPzfs6WO5GPgu3gOT9Nj4=
    MINIO_ROOT_USER: AgCmw+DYMamuniT/Mb95KJvi8cPpqhBqYUfvnAvTFnrXaijVe7AjP8+ihOIgI/H1A0OAo0rLP27r6McgZ18O8NNdfeSOmbQJQ/zI5fz/Cte1bx2xw4BAkWFVF5uKuogGzhu4wJiQB6W/pK1P0aIcZfQA8KA/f/+KtCa1i+fo/Y4IsZ31dDOAUmGRGk2m7eyDVYJQBr0PG34iZbXCZnex2rIhaUIlQDLkmBrlBhNYksKcR0QGtM85c/XflOT+/sL+yeZ6gUUg2Z0AaTotJxjGLpdHGx4WI7O3bc6M1u3l12C3CFLkBR9yldIGCKUEeTF4RlvAIoSgqXSlE70Fvu7zK0NLKP7Z3PNIs1heoS/sqEIAi9e9tZRLhtZFhvKy3mXjKXlyI/CCopxD/TpwGm3CMIVVBbZnvdO5dAC46ssAyrWBBBQ+AZNrBJKRzzYCZWxpe66loiOMZe+Fn68oyqvEcyjZTxYYPqF0jn+D9sLhmQ4Mf0k/G7Sk+pASQZnaibkFiwGRdtkp41YmBRAhQeHwcDS1NomSxHAYHXg8ApDxB1DcjntckkSztPH+X4j+uRC7inC4sdr6d7dMOAFvexAFsvRgGcY592Nr1WmWAiYxtgcDiBqgvtT81vlV9l4hLgLBzO29P4EK7IJR3dp37ylWqMCb/FRANS/+BvbSTkK0ZV5cnQrLoUsl/2KWYZK2NxrHiETWO08mkcVPe+c=
  template:
    metadata:
      name: minio-secret
      namespace: cloud-media
    type: Opaque
