
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: cloud-media
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: api
    - name: console
      protocol: TCP
      port: 9001
      targetPort: console
