// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/broker"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/persistence"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/storage"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/transcoder"
	"github.com/frozenf1sh/cloud-media/internal/usecase"
	"github.com/frozenf1sh/cloud-media/pkg/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWorker(cfg *config.Config) (*Worker, error) {
	string2 := provideRabbitMQURL(cfg)
	rabbitMQBroker, err := broker.NewRabbitMQBroker(string2)
	if err != nil {
		return nil, err
	}
	persistenceConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewGormDB(persistenceConfig)
	if err != nil {
		return nil, err
	}
	videoTaskRepository := persistence.NewVideoTaskRepository(db)
	fFmpegTranscoder, err := transcoder.NewFFmpegTranscoder()
	if err != nil {
		return nil, err
	}
	storageConfig := provideMinIOConfig(cfg)
	minIOStorage, err := storage.NewMinIOStorage(storageConfig)
	if err != nil {
		return nil, err
	}
	workerUseCase := usecase.NewWorkerUseCase(videoTaskRepository, fFmpegTranscoder, minIOStorage)
	database := persistence.NewDatabase(db)
	worker := NewWorker(rabbitMQBroker, workerUseCase, database)
	return worker, nil
}

// wire.go:

var workerProviderSet = wire.NewSet(broker.ProviderSet, persistence.ProviderSet, persistence.RepositoryProviderSet, storage.ProviderSet, transcoder.ProviderSet, usecase.ProviderSet, NewWorker,
	provideRabbitMQURL,
	provideDatabaseConfig,
	provideMinIOConfig,
)

func provideRabbitMQURL(cfg *config.Config) string {
	return cfg.RabbitMQ.URL
}

func provideDatabaseConfig(cfg *config.Config) *persistence.Config {
	return &persistence.Config{
		Host:     cfg.Database.Host,
		Port:     cfg.Database.Port,
		User:     cfg.Database.User,
		Password: cfg.Database.Password,
		DBName:   cfg.Database.DBName,
		SSLMode:  cfg.Database.SSLMode,
	}
}

func provideMinIOConfig(cfg *config.Config) *storage.Config {
	return &storage.Config{
		InternalEndpoint: cfg.MinIO.InternalEndpoint,
		InternalUseSSL:   cfg.MinIO.InternalUseSSL,
		ExternalEndpoint: cfg.MinIO.ExternalEndpoint,
		ExternalUseSSL:   cfg.MinIO.ExternalUseSSL,
		AccessKeyID:      cfg.MinIO.AccessKeyID,
		SecretAccessKey:  cfg.MinIO.SecretAccessKey,
	}
}
