// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/frozenf1sh/cloud-media/internal/adapter/rpc"
	"github.com/frozenf1sh/cloud-media/internal/domain"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/broker"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/persistence"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/storage"
	"github.com/frozenf1sh/cloud-media/internal/usecase"
	"github.com/frozenf1sh/cloud-media/pkg/config"
	"github.com/google/wire"
	"time"
)

// Injectors from wire.go:

func InitializeVideoServer(cfg *config.Config) (*Server, error) {
	persistenceConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewGormDB(persistenceConfig)
	if err != nil {
		return nil, err
	}
	outboxRepository := persistence.NewOutboxRepository(db)
	videoTaskRepository := persistence.NewVideoTaskRepository(db)
	processedMessageRepository := persistence.NewProcessedMessageRepository(db)
	rabbitMQBroker, err := provideRabbitMQBroker(cfg, processedMessageRepository)
	if err != nil {
		return nil, err
	}
	database := persistence.NewDatabase(db)
	outboxConfig := provideOutboxConfig(cfg)
	outboxService := usecase.NewOutboxService(outboxRepository, videoTaskRepository, processedMessageRepository, rabbitMQBroker, database, outboxConfig)
	objectStorageConfig := provideObjectStorageConfig(cfg)
	s3CompatStorage, err := storage.NewS3CompatStorage(objectStorageConfig)
	if err != nil {
		return nil, err
	}
	videoUseCase := usecase.NewVideoUseCase(outboxService, videoTaskRepository, s3CompatStorage)
	videoServer := rpc.NewVideoServer(videoUseCase)
	server := NewServer(videoServer, database, s3CompatStorage, outboxService)
	return server, nil
}

// wire.go:

var handlerProviderSet = wire.NewSet(persistence.ProviderSet, persistence.RepositoryProviderSet, storage.ProviderSet, usecase.ProviderSet, rpc.ProviderSet, provideRabbitMQBroker, wire.Bind(new(domain.ReliableMQBroker), new(*broker.RabbitMQBroker)), provideDatabaseConfig,
	provideObjectStorageConfig,
	provideOutboxConfig,
)

func provideRabbitMQBroker(cfg *config.Config, msgRepo domain.ProcessedMessageRepository) (*broker.RabbitMQBroker, error) {
	return broker.NewRabbitMQBroker(cfg.RabbitMQ.URL, msgRepo)
}

func provideDatabaseConfig(cfg *config.Config) *persistence.Config {
	return &persistence.Config{
		Host:     cfg.Database.Host,
		Port:     cfg.Database.Port,
		User:     cfg.Database.User,
		Password: cfg.Database.Password,
		DBName:   cfg.Database.DBName,
		SSLMode:  cfg.Database.SSLMode,
	}
}

func provideObjectStorageConfig(cfg *config.Config) *config.ObjectStorageConfig {
	return &cfg.ObjectStorage
}

func provideOutboxConfig(cfg *config.Config) usecase.OutboxConfig {
	return usecase.OutboxConfig{
		RecoveryInterval:  time.Duration(cfg.Outbox.RecoveryInterval) * time.Second,
		PendingTaskMaxAge: time.Duration(cfg.Outbox.PendingTaskMaxAge) * time.Minute,
		BatchSize:         cfg.Outbox.BatchSize,
		MaxRetries:        cfg.Outbox.MaxRetries,
	}
}
