// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/frozenf1sh/cloud-media/internal/adapter/rpc"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/broker"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/persistence"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/storage"
	"github.com/frozenf1sh/cloud-media/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeVideoServer() (*Server, error) {
	string2 := provideRabbitMQURL()
	rabbitMQBroker, err := broker.NewRabbitMQBroker(string2)
	if err != nil {
		return nil, err
	}
	config := provideDatabaseConfig()
	db, err := persistence.NewGormDB(config)
	if err != nil {
		return nil, err
	}
	videoTaskRepository := persistence.NewVideoTaskRepository(db)
	videoUseCase := usecase.NewVideoUseCase(rabbitMQBroker, videoTaskRepository)
	videoServer := rpc.NewVideoServer(videoUseCase)
	database := persistence.NewDatabase(db)
	server := NewServer(videoServer, database)
	return server, nil
}

// wire.go:

var handlerProviderSet = wire.NewSet(broker.ProviderSet, persistence.ProviderSet, persistence.RepositoryProviderSet, storage.ProviderSet, usecase.ProviderSet, rpc.ProviderSet, provideRabbitMQURL,
	provideDatabaseConfig,
	provideMinIOConfig,
)

func provideRabbitMQURL() string {
	return "amqp://guest:guest@localhost:5672/"
}

func provideDatabaseConfig() *persistence.Config {
	return persistence.NewDefaultConfig()
}

func provideMinIOConfig() *storage.Config {
	return &storage.Config{
		InternalEndpoint: "localhost:9000",
		InternalUseSSL:   false,
		ExternalEndpoint: "localhost:9000",
		ExternalUseSSL:   false,
		AccessKeyID:      "rootadmin",
		SecretAccessKey:  "rootpassword",
	}
}
