// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/frozenf1sh/cloud-media/internal/adapter/rpc"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/broker"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/persistence"
	"github.com/frozenf1sh/cloud-media/internal/infrastructure/storage"
	"github.com/frozenf1sh/cloud-media/internal/usecase"
	"github.com/frozenf1sh/cloud-media/pkg/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeVideoServer(cfg *config.Config) (*Server, error) {
	string2 := provideRabbitMQURL(cfg)
	rabbitMQBroker, err := broker.NewRabbitMQBroker(string2)
	if err != nil {
		return nil, err
	}
	persistenceConfig := provideDatabaseConfig(cfg)
	db, err := persistence.NewGormDB(persistenceConfig)
	if err != nil {
		return nil, err
	}
	videoTaskRepository := persistence.NewVideoTaskRepository(db)
	objectStorageConfig := provideObjectStorageConfig(cfg)
	s3CompatStorage, err := storage.NewS3CompatStorage(objectStorageConfig)
	if err != nil {
		return nil, err
	}
	videoUseCase := usecase.NewVideoUseCase(rabbitMQBroker, videoTaskRepository, s3CompatStorage)
	videoServer := rpc.NewVideoServer(videoUseCase)
	database := persistence.NewDatabase(db)
	server := NewServer(videoServer, database)
	return server, nil
}

// wire.go:

var handlerProviderSet = wire.NewSet(broker.ProviderSet, persistence.ProviderSet, persistence.RepositoryProviderSet, storage.ProviderSet, usecase.ProviderSet, rpc.ProviderSet, provideRabbitMQURL,
	provideDatabaseConfig,
	provideObjectStorageConfig,
)

func provideRabbitMQURL(cfg *config.Config) string {
	return cfg.RabbitMQ.URL
}

func provideDatabaseConfig(cfg *config.Config) *persistence.Config {
	return &persistence.Config{
		Host:     cfg.Database.Host,
		Port:     cfg.Database.Port,
		User:     cfg.Database.User,
		Password: cfg.Database.Password,
		DBName:   cfg.Database.DBName,
		SSLMode:  cfg.Database.SSLMode,
	}
}

func provideObjectStorageConfig(cfg *config.Config) *config.ObjectStorageConfig {
	return &cfg.ObjectStorage
}
