apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-agent-config
  namespace: cloud-media
data:
  config.yaml: |
    receivers:
      # 采集容器和 K3s 节点指标
      kubeletstats:
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        auth_type: "serviceAccount"
        insecure_skip_verify: true
        collection_interval: 20s

      # 采集宿主机底层指标
      hostmetrics:
        collection_interval: 20s
        scrapers:
          cpu: {}
          memory: {}
          load: {}
          disk: {}
          network: {}
          filesystem: {}

      filelog:
        include: [/var/log/pods/*/*/*.log]
        include_file_path: true
        start_at: beginning
        operators:
          - type: container
          - type: remove
            field: attributes.log_file_path

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      # 自动给指标打上 Pod Name, Namespace 等标签，否则 Grafana 面板无法筛选
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.namespace.name
            - k8s.node.name
            - k8s.deployment.name
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: connection

      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 8192
        timeout: 200ms
      resource:
        attributes:
          - action: insert
            key: k8s.cluster.name
            value: cloud-media-cluster

    exporters:
      otlp:
        endpoint: otelcol-gateway-service:4317
        tls:
          insecure: true
      otlphttp:
        endpoint: http://otelcol-gateway-service:4318
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: info
      pipelines:
        logs:
          receivers: [filelog]
          processors: [k8sattributes, memory_limiter, resource, batch]
          exporters: [otlphttp]
        traces:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, resource, batch]
          exporters: [otlp]
        metrics:
          # 将新加的接收器放入指标流水线
          receivers: [otlp, kubeletstats, hostmetrics]
          processors: [k8sattributes, memory_limiter, resource, batch]
          exporters: [otlp]
