apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-agent
  namespace: cloud-media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-agent
rules:
  # 1. 日志采集需要的权限
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  
  # 2. kubeletstats 接收器必须的权限 (获取节点指标)
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy", "nodes/metrics"]
    verbs: ["get", "watch", "list"]

  # 3. k8sattributes 处理器需要的权限 (关联 Pod 信息)
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-agent
subjects:
  - kind: ServiceAccount
    name: otelcol-agent
    namespace: cloud-media
roleRef:
  kind: ClusterRole
  name: otelcol-agent
  apiGroup: rbac.authorization.k8s.io
