
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-agent
  namespace: cloud-media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-agent
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-agent
subjects:
  - kind: ServiceAccount
    name: otelcol-agent
    namespace: cloud-media
roleRef:
  kind: ClusterRole
  name: otelcol-agent
  apiGroup: rbac.authorization.k8s.io
