
apiVersion: v1
kind: Service
metadata:
  name: otelcol-gateway-service
  namespace: cloud-media
spec:
  selector:
    app: otelcol-gateway
  type: ClusterIP
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: otlp-http
