---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: cloud-media
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAv7pmvCtdFlnRgjPrADby6MXJooaeXnAEhrFz9BDvcw5vbxt1PfsGwsiyiPTPhBRSkOJkYR23+SuwzVHCAXzOPRMF1z0Z/DimW57QWRkFKD2hkcFG9iEqDVZGFp6zTcpSNf5vFxUcrLiVXAA95/YodL2kybtBv0kmYSVW6d+81mWL5F1LedkDhmfwnnlNCJnHj9xjB6+6KiXACi+UzGgyNut4T6HBmTrJ7iLtYQ+Pzar9TpDLaxtyg9RaDbKyPpaQEggDMEwXbe+Sx92uynTi4qRjFL5RM/rEVepEGCJoZ+ANSNarCOvEYWiTBYVpUdb7cx6QOb3QO7jiRIvqwzi7U+//cxGDpwBTwmKRcY3APFFQr1UpYIp23poGs5iE68v9QSmrqpFnlSmaacQixg+SQC1kls2KTQ8jbqV+fiRZFlSYLdhqFpt0MISmumy3n9k3yY2JkNozGtwGoc32bLZ7hDtyRCbnd/AKD/tyVScJGrHnkxdpEFFMzcFi70afSCUVaY49jgr2sTSpI/hx3KD2b2oAi6AnDQjyABQYhwUjWufSmmQcqwBdHUiII//lM9otnbKKp850bihvBpd87zGv2lAhe7w2nUkwQulxR73594uT2ZFRt2V57tWmZTi4qgvd0Id3xDfnWB04axVS+nCb2p5sRUCV24Rrk3i70iu59EicdeIST6tBxvh66Es9ivNbo9xMM3A==
    RABBITMQ_DEFAULT_USER: AgCWQyyGngMNc4Kq4lCkj9yu43oHqmRKgOw12d06OPVYDyJg9P51//iXDP40yclRswUd+7BiY1GQUEoRj4V4h/2pTG9o9Ar/JGm8LgL2hdiSEV2KMYMfri0nx8bdaCh136wOV+BaTAao0m7EKvmR1zhR/y2xTTj/WFhCSJP1g4TwniD+fqDixT7tzXtJxqWk0d175Scfjr66Ko8vnoPIXz+R/oZeIO5l0IS3NketZDR2KnKQnMtPBisbRKqjewk37TncUnha3uHYM27AGBe1Dp9DOQpJTEQ9dUZZ4sY63FoBIZ3KcqanBWOj0ek4tLh6LONcrf5ik90r1d19zS6AILTZqFcjVeWPE6oHoZ99dlS95fALG1dYxiAwmc2i1Ped+Fn2BX0rmK7OTwrEVOrm0WHmIHZ+EN5nxt8fkJVHu3YEysXNRrsvtLk3toGxe1VN/wRtlglaK5XqRQNWHv6f7tKTdm0cbRJujSr/8dmCm3UEmxBbLJZyHK1aZTdvgvfGAUaiEocPwpPo1lZmNLy4mm902C7HfM+symvPCE+lR/1N8YwDu4TgsIGShseV85nPzMEGHBOkbH7GSSfWPm9VZXeotp9CS9I+KbjtHJpIvmibgqpVhVMT+VyKcxG1App0wCKe1fGg0XllI/0ZdbRDPFFpS7o5r6TwfnI1IxskfyH0eTc9pSU1GrzYQGzT82ttNAjeTnWrzQ==
  template:
    metadata:
      name: rabbitmq-secret
      namespace: cloud-media
    type: Opaque
