
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: cloud-media
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: management
      protocol: TCP
      port: 15672
      targetPort: management
