
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-media
resources:
  - common-configmap.yaml
  - secrets.yaml
  - worker-prestop-script.yaml
  - api-server/service.yaml
  - api-server/deployment.yaml
  - worker/deployment.yaml
