
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-media
resources:
  # Postgres
  - postgres/secrets.yaml
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  # RabbitMQ
  - rabbitmq/secrets.yaml
  - rabbitmq/pvc.yaml
  - rabbitmq/service.yaml
  - rabbitmq/statefulset.yaml
  # MinIO
  - minio/secrets.yaml
  - minio/pvc.yaml
  - minio/service.yaml
  - minio/statefulset.yaml

