---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: cloud-media
spec:
  encryptedData:
    MINIO_ACCESS_KEY_ID: AgAgLDBdP+4F/9Dx9qdYx8r595uqIW5oJi2fhWjyu09SZ/tfcMFhcmXWwYAhMac6h8J0aWPfgLMGdk/oXeeIdXTlTSLLpY6EX8MX7L7KtdowCmkdBlBqX5tMpV9+KtvYKb/Aqy32hVCjm02bB8QL6jv/86wZqbpFoIsrnw+X4LuWyiwu4acIC0fwBGF64IBdtBJrfcokU/AkZaRePEZjJbRB58BA96Ne57rEPbcLG84cOC4lxgO/TqibOdShFYEUScRtJdNCFXzq07iYmFoAxaSh9pyyYM/LN6A4wDgKmf/PSb4KQZA6x5qo+V84/DGkLizaPf5ZDG2U4XuO1/SzWSsdQhjYxjaIriJV732fBQX6+dEQdeO9cTRWPLZn9VauEgTF3O3zuweQAlielYNGHOpzE6BQTL4OXKW20z5r29hj5/TjOxRq9qVAyhukaRYQ4ONXFT4s4bKiUo/bboR/GwNVT2M6fjouiuSnps/jjCg87FUWILPz2H2jLvtB35522aFnR79+6HbHa9FTxsHIminB8rgzbN6OBlGIeHIgx28o1YwuomiIo8wlTpjWJ0f15Fnam8yzP0jNL+6dHladPq6bB1iZvaBbacQdFZU81TDEcUqbSNM5YK0HFfZP/umJ2i1Ow/+yR1n0qQbKs18x0JwMNR+A0NfJ/cPdCLPJIzWVrb50MAA87EUyIa+esGRG3//VmdGzAj7sOTA=
    MINIO_SECRET_ACCESS_KEY: AgBQ4SofLUgfvAHH5mrjjrJwlKw8/uEKKMgzQDJGSYg1GLK4mlKp14/YkHc2hPCcc0ncZcyo8SCSwcbnaC+jZeJfbA+2lAjHvYeqYQA4P9NDIKHZlWJcXORLacuISaWXgoCAwIucSuL6DIIFj2jteIayYuJbloYYcltbUyF1t8B2ahULv8Yu3upb6MttOt/NPIVsXZ+EE2SgoDx4nvfrT69/I5083cHjstecsrNmOneDu+Kjgy2ky7pxC1BYAXlSGa9F8w3nfw6SVLs9ujugcDHk1TiY+k1E/g9vdgwi4/6aB84YDDR0KMFQZhYavvYPqdeEwe2PMqj0Uy74WDbu1X/J+4vicqiOMwcX2Ep+8xrWcnyWESBHNNTHR7FzAX3zeGvhO5Rb/CCgYWI7g6gdOfBWT8xle6o3q1xLee0JVm5B/yyWeKzMsSf5abNvhvAYJDnZFecdgX03n5NdENvoP8n1ekw/p+JST0AHqVwwLFUxUxdtMx+o5Z+bTIo1aAulhKH0kYLvnlI7k2aNyodLPmDgPP7QUfqV8Wkkt4TYsQG86qZjpOH/n8EeHTU3FPWyxxD9KWfMDleeJ0c+hbT8rPAA/6OKpjo7dS1HxTJdIagJGKB+99tGdUZ3N6W/um7ToS1dUbO5didzh3tJVce9PeB5flmGOagJgok2gSLqrw/soliBFKR4Vn/ZTOUmGnlKzq/KYOYSmP2hTtZIjNo=
  template:
    metadata:
      name: minio-credentials
      namespace: cloud-media
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: cloud-media
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAvPuaOZvr7d2kaU2W2hpdi3dzmt1GvQH4sSFTmkdwGQ6kGsfWXWG+mYicy5cWDpvieZeLaS4355i6FPS2pgHxDeH8Gt0CYzqOg1FpJCWL/EG74hAhi115Ji0D5q5hpCz3jyYD69a1AmB8X1YKl9M0/7f7T61VMxaC+UFTAawrB3S/oxw3j7K3dSA4y//ohmae6yxQR194bRlSUTW/8N2dw38ylte1MG1KkUjbaY2syH0qZFFXWCJb1mdAqa1GMQSDs1cGajQW0dqnbP1Uw/MxxeGcZnXHAWkZqCi9wkm1RDoiIPAKXCx5oqFrMJRoQPfp6bjaKY1LDPMvp5dElSP1LNsVtfEbbaKcadH+fp3Ientt0bqzaMk0+xHpOQMbaBjmuXiQ77aw6LMdR0bexCAGuXfUc5KeqB9ygd07FRNwSAy98Kb5LdfqGdb4f1sRDAS1pm0Sk75NYNOR8P12mkQpVTbThRa6e8b/zzU9GRgqjI362Nk23Q4gwRq3tPKCFtprrhgTzk5lW24Kj9zmQLCG8S0hMBUcdX55D2qSuWxHFtcaCXsrWnqXK7oyhOc62lQMaAk83d2LAIMlmHVnzAOr67o701/Ka0xENsgdr7nxnAoG3kZdlF/itYEd/2b7SwEkazEhrmTzzMQKg6tf2O3TD4AZlE9y/LYgMUBdNXuCdcLCgFEGue/oLCuOWk8SutJK3aHC8LizYyQ==
    GF_SECURITY_ADMIN_USER: AgAQUHP/Xoh2p2whuG9SLCs8LTFOpBW9Hqye/d2HJAkbjAI87YgLoqRZ4KOdFGpJN2IuKmcJ8hsw7RIYXKnoCZd0leeeqPm3rLzd2Jy15DlA/TpvChgzhzUPjnCIQe/Fmk6IKjGDuMEKdBLIQLZc7+auHx1rCQH1ZrXIx+NwCt3fF09lSDXMnGv5qf6yF3d7g34wIEWZHBQP1s1ZsFSYi4HJQDn7MyzFeCdYsJ/RQs3zRNyhQY+oglpj0TQq9BFdDiItR03xs9m+DwTeRt5kO0ACPQfXHqBriaQ0uoVaHZLWDpM7gz4HeWCM/hz4scr0X3cM9pxBFaur2WnaxTtS9HKH0I2dlsvQO09Yxmby83xykR1+Aphpg1VTauma6l8/M946NSdWM7cSjFm22yPfumwPhje+MJTN7gOdXfNUinN3EgPrxna6GtcMmO5/ImlexAURnEXI3iU97GGJZLnGxvz5+vC5Qk5EeMhfN/SOoL46Pq13h6yVPJCVIjPXuTKXFpgSuMn7zbxxtOo6z4DgSWJhtR/droLyb8F0wMdlNtZv2ZhhUiG6phEnKAf+6dnawr636aMOdga7g1Dnbw11pocO47qT8K9EFwER7tP7siujjLeW71V8kR4VrZyQHiO21iTtNIjUQMDTvWo42LOqjHyX89Id5qDQvDHofYAKkpz+aHnINc5BKaEWN1e1EZbBaZOL3RsrXA==
  template:
    metadata:
      name: grafana-credentials
      namespace: cloud-media
    type: Opaque
